### ISSUE TITLE
Sentinel Docker node stopped working several days ago

### ISSUE THREAD

**Issue by miguel-a-calles-mba** [sentinel-official/sentinel#197]
See the logs below.

```
[2021-04-09 15:51:56 +0000] [31] [INFO] Booting worker with pid: 31
[2021-04-09 15:51:56 +0000] [8] [DEBUG] 1 workers

/usr/lib/python2.7/site-packages/speedtest_cli.py:34: UserWarning: The file speedtest_cli.py has been deprecated in favor of speedtest.py
and is available for download at:

https://raw.githubusercontent.com/sivel/speedtest-cli/master/speedtest.py
  warnings.warn(DEPRECATED_MSG, UserWarning)
Traceback (most recent call last):
  File "app.py", line 72, in <module>
    node = Node(config)
  File "/root/sentinel/node/node.py", line 13, in __init__
    self.speed_test = Speedtest()
  File "/usr/lib/python2.7/site-packages/speedtest.py", line 1091, in __init__
    self.get_config()
  File "/usr/lib/python2.7/site-packages/speedtest.py", line 1174, in get_config
    map(int, server_config['ignoreids'].split(','))
ValueError: invalid literal for int() with base 10: ''
```

**Comment by joelrb** [comment]
I have the same issue. I just installed it on Ubuntu.

**Comment by miguel-a-calles-mba** [comment]
I tried the Tendermint mode and received a similar error.

```
I[04-09|17:05:03.255] REST server started                          module=rest-server 
Traceback (most recent call last):
  File "app.py", line 7, in <module>
    from sentinel.config import DEFAULT_GAS
  File "/root/sentinel/__init__.py", line 2, in <module>
    from .node import node
  File "/root/sentinel/node/__init__.py", line 2, in <module>
    from .controllers import add_tx
  File "/root/sentinel/node/controllers.py", line 3, in <module>
    from .node import node
  File "/root/sentinel/node/node.py", line 74, in <module>
    node = Node()
  File "/root/sentinel/node/node.py", line 13, in __init__
    self.speed_test = Speedtest()
  File "/usr/lib/python2.7/site-packages/speedtest.py", line 1053, in __init__
    self.get_config()
  File "/usr/lib/python2.7/site-packages/speedtest.py", line 1136, in get_config
    map(int, server_config['ignoreids'].split(','))
ValueError: invalid literal for int() with base 10: ''
```

**Comment by llawliet11** [comment]
@miguel-a-calles-mba you can download speedtest.py and map it to speedtest_cli.py in the container. For example, i downloaded the file and store at /root/speedtest.py, then add this to the command `--mount type=bind,source=/root/speedtest.py,target=/usr/lib/python2.7/site-packages/speedtest_cli.py` 

Full command:
`sudo docker run -it -exec --privileged --mount type=bind,source=/root/speedtest.py,target=/usr/lib/python2.7/site-packages/speedtest_cli.py --mount type=bind,source=$HOME/.sentinel,target=/root/.sentinel -p 3000:3000 -p 1194:1194/udp sentinelofficial/sentinel-vpn-node`
