### ISSUE TITLE
Windows 10 setup issue

### ISSUE THREAD

**Issue by Damozzie** [sentinel-official/sentinel#48]
Hi, 

I opened the Sentinel wallet yesterday .. (don’t know how but not as administrator). Attempting to follow instruction I closed it, deleted app data, sentinel and squirrel temp files and downloaded again, now I can’t load it getting error message   Installation has failed.   I’m running Windows 10. I managed to untick view hidden item also so I may have deleted an essential file although my computer is running fine. 

Here’s the setup log
2018-04-18 23:38:12> Program: Starting Squirrel Updater: --install .
2018-04-18 23:38:12> Program: Starting install, writing to C:\Users\NewUser\AppData\Local\SquirrelTemp
2018-04-18 23:38:12> Program: About to install to: C:\Users\NewUser\AppData\Local\Sentinel
2018-04-18 23:38:12> IEnableLogger: Failed to copy Update.exe to C:\Users\NewUser\AppData\Local\Sentinel\Update.exe: System.UnauthorizedAccessException: Access to the path 'C:\Users\NewUser\AppData\Local\Sentinel\Update.exe' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at System.IO.File.Copy(String sourceFileName, String destFileName, Boolean overwrite)
   at Squirrel.Update.Program.<>c__DisplayClass4_1.<Install>b__4()
   at Squirrel.Utility.LogIfThrows(IFullLogger This, LogLevel level, String message, Action block)
2018-04-18 23:38:12> Unhandled exception: System.AggregateException: One or more errors occurred. ---> System.UnauthorizedAccessException: Access to the path 'C:\Users\NewUser\AppData\Local\Sentinel\Update.exe' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at System.IO.File.Copy(String sourceFileName, String destFileName, Boolean overwrite)
   at Squirrel.Update.Program.<>c__DisplayClass4_1.<Install>b__4()
   at Squirrel.Utility.LogIfThrows(IFullLogger This, LogLevel level, String message, Action block)
   at Squirrel.Utility.ErrorIfThrows(IEnableLogger This, Action block, String message)
   at Squirrel.Update.Program.<Install>d__4.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Squirrel.Update.Program.executeCommandLine(String[] args)
   at Squirrel.Update.Program.main(String[] args)
---> (Inner Exception #0) System.UnauthorizedAccessException: Access to the path 'C:\Users\NewUser\AppData\Local\Sentinel\Update.exe' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at System.IO.File.Copy(String sourceFileName, String destFileName, Boolean overwrite)
   at Squirrel.Update.Program.<>c__DisplayClass4_1.<Install>b__4()
   at Squirrel.Utility.LogIfThrows(IFullLogger This, LogLevel level, String message, Action block)
   at Squirrel.Utility.ErrorIfThrows(IEnableLogger This, Action block, String message)
   at Squirrel.Update.Program.<Install>d__4.MoveNext()<---

**Comment by Daschesc** [comment]
2018-04-18 23:38:12> Program: Starting Squirrel Updater: --install .
2018-04-18 23:38:12> Program: Starting install, writing to C:\Users\NewUser\AppData\Local\SquirrelTemp
2018-04-18 23:38:12> Program: About to install to: C:\Users\NewUser\AppData\Local\Sentinel
2018-04-18 23:38:12> IEnableLogger: Failed to copy Update.exe to C:\Users\NewUser\AppData\Local\Sentinel\Update.exe: System.UnauthorizedAccessException: Access to the path 'C:\Users\NewUser\AppData\Local\Sentinel\Update.exe' is denied.
at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)

This error states there was no authorization to write files to the directories it targets - The administrator account must be used to install the client and allow it to write to the program directories.

**Comment by fabulous345** [comment]
We are not able to find where the issue is. We are working on it. Hope it will not be same in the next release. Please wait for it. Thanks.
